//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.03 at 06:00:00 PM EEST 
//


package codegen.util.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="swagger" type="{http://www.example.org/codegen/}SwaggerType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "configuration")
public class Configuration {

    @XmlElement(required = true)
    protected SwaggerType swagger;

    /**
     * Gets the value of the swagger property.
     * 
     * @return
     *     possible object is
     *     {@link SwaggerType }
     *     
     */
    public SwaggerType getSwagger() {
        return swagger;
    }

    /**
     * Sets the value of the swagger property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwaggerType }
     *     
     */
    public void setSwagger(SwaggerType value) {
        this.swagger = value;
    }

}
